name: CD

on:
    push:
        tags:
            - "*"

jobs:
    integration-test:
        name: Integration test on (${{ matrix.os }} node ${{ matrix.node-version }})

        strategy:
            matrix:
                os: [windows-latest]
                node-version: [14]

        runs-on: ${{ matrix.os }}

        steps:
            - name: checkout
              uses: actions/checkout@v2

            - name: get-tag
              uses: olegtarasov/get-tag@v2.1
              with:
                  # Optional. Returns specified group text as tag name. Full tag string is returned if regex is not defined.
                  tagRegex: '^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*)$'
            - name: validate-tag
              with:
                  tagname: ${{ steps.tagName.outputs }}
              run: |
                  echo $tagname
