name: CD

on:
    push:
        tags:
            - "*"

jobs:
    integration-test:
        name: Integration test on (${{ matrix.os }} node ${{ matrix.node-version }})

        strategy:
            matrix:
                os: [ubuntu-latest]
                node-version: [14]

        runs-on: ${{ matrix.os }}

        steps:
            - name: checkout
              uses: actions/checkout@v2

            - id: tagName
              uses: olegtarasov/get-tag@v2.1
              with:
                  tagRegex: '^((0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)))\+(?<path>.[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*)$'

            - name: validation and set params
              run: |
                  if [ -z "${{ steps.tagName.outputs.path }}" ]; then
                    echo "emply path"
                    exit 1;
                  fi;
                  if [ -z "${{ steps.tagName.outputs.tag }}" ]; then
                    echo "emply tag"
                    exit 1;
                  fi;
