name: CD

on:
    push:
        tags:
            - "*"

jobs:
    integration-test:
        name: Integration test on (${{ matrix.os }} node ${{ matrix.node-version }})

        strategy:
            matrix:
                os: [ubuntu-latest]
                node-version: [14]

        runs-on: ${{ matrix.os }}

        steps:
            - name: checkout
              uses: actions/checkout@v2

            - name: semantic-versioning-tag
              uses: LongOddCode/semantic-versioning-tag@0.1.0
              id: tagName

            - name: validation and set params
              run: |
                  echo "${{ steps.tagName.outputs}}":
