name: CD

on:
    push:
        tags:
            - "*"

jobs:
    integration-test:
        name: Integration test on (${{ matrix.os }} node ${{ matrix.node-version }})

        strategy:
            matrix:
                os: [ubuntu-latest]
                node-version: [14]

        runs-on: ${{ matrix.os }}

        steps:
            - name: checkout
              uses: actions/checkout@v2

            - id: tagName
              uses: olegtarasov/get-tag@v2.1
              with:
                  tagRegex: /^(?<major>0|[1-9]\d*)\.(?<minor>0|[1-9]\d*)\.(?<patch>0|[1-9]\d*)(?:-(?<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/gm

            - name: validation and set params
              run: |
                  echo "${{ steps.tagName.outputs}}":
