name: CI

on:
    push:
        tags:
            - 1.2.0-rc.*

jobs:
    azure:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              run: |
                  git branch

            - name: Build VSIX
              run: |
                  echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
